DynamoLeagueBlazor/Client/Features/Fines/List.razor

Fix Bug #23 Only show Actions icon for Admins of the site.

#23  Fines “Actions” table column is showing up for non admins

---

DynamoLeagueBlazor/Client/Features/Players/AddFine.razor
DynamoLeagueBlazor/Client/Features/Players/AddFine.razor.cs

Add fine skeleton

---

DynamoLeagueBlazor/Client/Features/Admin/StartSeason.razor
DynamoLeagueBlazor/Client/Features/Admin/StartSeason.razor.cs
DynamoLeagueBlazor/Client/Features/Dashboard/TopOffenders/TopOffenders.razor
DynamoLeagueBlazor/Client/Features/Fines/List.razor
DynamoLeagueBlazor/Client/Features/FreeAgents/Detail.razor
DynamoLeagueBlazor/Client/Features/FreeAgents/List.razor
DynamoLeagueBlazor/Client/Features/Players/List.razor
DynamoLeagueBlazor/Client/Features/Rules/Rules.razor
DynamoLeagueBlazor/Client/Features/Teams/List.razor
DynamoLeagueBlazor/Client/Shared/Components/PageHeader.razor

Adjust page headers

---

DynamoLeagueBlazor/Client/Features/Rules/Cost.razor
DynamoLeagueBlazor/Server/Features/Teams/Detail.cs
DynamoLeagueBlazor/Server/Features/Teams/List.cs
DynamoLeagueBlazor/Shared/Utilities/CapSpaceUtilities.cs
DynamoLeagueBlazor/Tests/Features/Teams/DetailTests.cs
DynamoLeagueBlazor/Tests/Utilities/CapSpaceTests.cs

#17 - Fix Current Cap Space Logic calculation
Added Unit Tests
Updated Teams Detail and List API to pass date.

Fixed Incorrect Current Cap Space Logic

---

DynamoLeagueBlazor/Server/Models/Player.cs
DynamoLeagueBlazor/Tests/Features/FreeAgents/AddBidTests.cs

Extend free agency when a bid is made

---

DynamoLeagueBlazor/Client/Features/Fines/List.razor
DynamoLeagueBlazor/Client/Features/Fines/List.razor.cs
DynamoLeagueBlazor/Client/Features/Players/AddFine.razor
DynamoLeagueBlazor/Client/Features/Players/List.razor
DynamoLeagueBlazor/Client/Features/Players/List.razor.cs
DynamoLeagueBlazor/Client/Features/Teams/Detail.razor
DynamoLeagueBlazor/Server/Features/Players/List.cs
DynamoLeagueBlazor/Server/Features/Teams/Detail.cs
DynamoLeagueBlazor/Shared/Features/Fines/List.cs
DynamoLeagueBlazor/Shared/Features/Players/List.cs
DynamoLeagueBlazor/Shared/Features/Teams/Detail.cs
DynamoLeagueBlazor/Tests/Features/Fines/ListTests.cs
DynamoLeagueBlazor/Tests/Features/Players/ListTests.cs
DynamoLeagueBlazor/Tests/Features/Teams/DetailTests.cs

Fix unmapped columns

---

DynamoLeagueBlazor/Client/Features/Fines/List.razor
DynamoLeagueBlazor/Client/Features/FreeAgents/List.razor
DynamoLeagueBlazor/Client/Features/Teams/Detail.razor
DynamoLeagueBlazor/Client/Features/Teams/List.razor
DynamoLeagueBlazor/Client/Shared/MainLayout.razor
DynamoLeagueBlazor/Client/Shared/NavMenu/NavMenu.razor

- Added mobile navbar
- Fix a bug  saw on free agent bid amount on mobile
- Swap colors on Team chips because they were hard to read
closes #30

Mobile navbar & misc display changes

---

DynamoLeagueBlazor/Tests/Utilities/FineUtilitiesTests.cs

Rest of tests emerged in #49 
closes #28

Add fine utility tests

---

DynamoLeagueBlazor/Client/Features/Admin/AddPlayer.razor
DynamoLeagueBlazor/Client/Features/Admin/AddPlayer.razor.cs
DynamoLeagueBlazor/Tests/DynamoLeagueBlazor.Tests.csproj
DynamoLeagueBlazor/Tests/Features/Admin/AddPlayerServerTests.cs
DynamoLeagueBlazor/Tests/Features/Admin/AddPlayerTests.cs
DynamoLeagueBlazor/Tests/GlobalUsings.cs
DynamoLeagueBlazor/Tests/IntegrationTesting.cs
DynamoLeagueBlazor/Tests/UITestBase.cs

Add one small set of tests for add player. more prs incoming

Add UI tests for adding a player

---

DynamoLeagueBlazor/Client/Features/OfferMatching/List.razor
DynamoLeagueBlazor/Client/Features/OfferMatching/List.razor.cs
DynamoLeagueBlazor/Server/Features/OfferMatching/List.cs
DynamoLeagueBlazor/Server/Infrastructure/SeedDataCommand.cs
DynamoLeagueBlazor/Server/Models/Player.cs
DynamoLeagueBlazor/Server/Program.cs
DynamoLeagueBlazor/Shared/Features/OfferMatching/List.cs
DynamoLeagueBlazor/Tests/Features/OfferMatching/ListTests.cs
DynamoLeagueBlazor/Tests/Models/PlayerTests.cs

Thanks to 🔥🔥@andrewD713🔥🔥
🔥🔥@shalsten🔥🔥

Add offer matching list

---

src/Client/Features/Admin/RefreshPlayerHeadshots.razor
src/Client/Features/Admin/RefreshPlayerHeadshots.razor.cs
src/Client/Features/Admin/StartSeason.razor
src/Client/Shared/NavMenu/Admin.razor
src/Server/Features/Admin/RefreshPlayerHeadshots.cs
src/Server/Models/Player.cs
src/Server/Program.cs
src/Shared/Features/Admin/RefreshPlayerHeadshots.cs
src/Tests/Features/Admin/RefreshPlayerHeadshotsTests.cs
src/Tests/IntegrationTestBase.cs

#73 part one
I still need to add this feature to individual “Add Player”

Automatic* player headshots

---

src/Client/Features/Admin/AddPlayer.razor
src/Client/Features/Dashboard/Shared/RankedCard.razor
src/Client/Features/FreeAgents/Detail.razor
src/Client/Features/Teams/List.razor
src/Client/Shared/Components/Avatar.razor
src/Client/Shared/Components/NameWithImage.razor
src/Tests/Shared/Components/AvatarTests.cs

Provide an alternative when a player headshot is missing.

---

src/Client/Features/FreeAgents/List.razor
src/Server/Features/FreeAgents/List.cs
src/Shared/Features/FreeAgents/List.cs
src/Tests/Features/FreeAgents/ListTests.cs

Include the winning team as a badge

---

src/Client/Features/FreeAgents/Detail.razor.cs
src/Client/Program.cs
src/Server/Features/FreeAgents/AddBid.cs
src/Server/Program.cs
src/Shared/Features/FreeAgents/AddBid.cs
src/Tests/Features/FreeAgents/AddBidTests.cs
src/Tests/GlobalUsings.cs

Hard enforce bid validation

---

src/Client/Features/FreeAgents/Detail.razor
src/Server/Features/FreeAgents/Detail.cs
src/Server/Infrastructure/SeedDataCommand.cs
src/Tests/Features/FreeAgents/DetailTests.cs
src/Tests/Features/Teams/SignPlayerTests.cs

Refresh timeline view

---

src/Server/Models/Player.cs
src/Server/Program.cs
src/Tests/FakeFactory.cs
src/Tests/Features/OfferMatching/ExpireOfferMatchingTests.cs
src/Tests/Features/OfferMatching/ListTests.cs
src/Tests/Models/PlayerTests.cs

Fix offer matching

---

src/Client/Program.cs
src/Server/Program.cs

Add user id when anything is logged

---

src/Client/DynamoLeagueBlazor.Client.csproj
src/Client/Features/Admin/Users/List.razor
src/Client/Features/Fines/List.razor
src/Client/Features/FreeAgents/BidCountdown.razor
src/Client/Features/FreeAgents/List.razor
src/Client/Features/OfferMatching/List.razor
src/Client/Features/Players/List.razor
src/Client/Features/Teams/Detail.razor
src/Client/Shared/MainLayout.razor
src/Client/wwwroot/css/app.css
src/Client/wwwroot/index.html

Because people need glasses :P 
Closes #130

Add striping to tables for mobile view

---

src/Client/DynamoLeagueBlazor.Client.csproj
src/Client/Features/Admin/AddPlayer.razor.cs
src/Client/Features/Admin/Users/Delete.razor.cs
src/Client/Features/Admin/Users/List.razor.cs
src/Client/Features/Dashboard/TopOffenders.razor.cs
src/Client/Features/Dashboard/TopTeamFines.razor.cs
src/Client/Features/Fines/List.razor.cs
src/Client/Features/Fines/Manage.razor.cs
src/Client/Features/FreeAgents/Detail.razor.cs
src/Client/Features/FreeAgents/List.razor.cs
src/Client/Features/OfferMatching/List.razor.cs
src/Client/Features/Players/AddFine.razor.cs
src/Client/Features/Players/List.razor.cs
src/Client/Features/Teams/Detail.razor.cs
src/Client/Features/Teams/List.razor.cs
src/Client/Features/Teams/SignPlayer.razor.cs
src/Client/Program.cs

Add retry policy and remove calls for AccessTokenNotAvailable

---

src/Client/Features/OfferMatching/List.razor
src/Client/Features/OfferMatching/List.razor.cs
src/Server/Features/Authentication/OidcConfigurationController.cs
src/Server/Features/OfferMatching/List.cs
src/Server/Features/OfferMatching/MatchPlayer.cs
src/Server/Models/Player.cs
src/Server/Program.cs
src/Shared/Features/OfferMatching/List.cs
src/Shared/Features/OfferMatching/MatchPlayer.cs
src/Tests/Features/FreeAgents/BidCountdownTests.cs
src/Tests/Features/OfferMatching/ListTests.cs
src/Tests/Features/OfferMatching/MatchPlayerTests.cs

Show offer matching for everyone but only matching team can actually match.

---

src/Client/Shared/MainLayout.razor
src/Client/Shared/UpdateAvailableDetector.razor
src/Client/wwwroot/index.html
src/Client/wwwroot/service-worker-registrator.js
src/Tests/Shared/UpdateAvailableDetectorTests.cs

Attempt to fix PWA functionality by adding an alert for clients to update

---

src/Server/Models/Team.cs
src/Tests/Models/BidTests.cs

Closes #27 
Doesn't need released by itself - no production code changed.

Add unit tests for model classes

---

README.md
src/Client/Shared/MainLayout.razor
src/Shared/Features/Admin/AddPlayer.cs
src/Shared/Features/Teams/Detail.cs

#142 & #141

---

.github/workflows/dotnet.yml
src/Server/Program.cs
src/Server/appsettings.Development.json
src/Server/appsettings.Production.json
src/Server/appsettings.json

Also added an environment variable to our hosting platform of ASPNETCORE_ENVIRONMENT = PRODUCTION
Closes #145

Add IssuerUri to identity with production environment

---

src/Server/Program.cs

Change to other approach

---

src/Tests/Features/Admin/AddPlayerTests.cs
src/Tests/Features/Admin/RefreshPlayerHeadshotsTests.cs
src/Tests/Features/Admin/StartSeasonTests.cs
src/Tests/Features/Admin/Users/DeleteTests.cs
src/Tests/Features/Admin/Users/ListTests.cs
src/Tests/Features/Dashboard/TopOffendersTests.cs
src/Tests/Features/Dashboard/TopTeamFinesTests.cs
src/Tests/Features/Fines/ListTests.cs
src/Tests/Features/Fines/ManageFineTests.cs
src/Tests/Features/FreeAgents/AddBidTests.cs
src/Tests/Features/FreeAgents/DetailTests.cs
src/Tests/Features/FreeAgents/EndBiddingTests.cs
src/Tests/Features/FreeAgents/ListTests.cs
src/Tests/Features/OfferMatching/ExpireOfferMatchingTests.cs
src/Tests/Features/OfferMatching/ListTests.cs
src/Tests/Features/OfferMatching/MatchPlayerTests.cs
src/Tests/Features/Players/AddFineTests.cs
src/Tests/Features/Players/FineDetailTests.cs
src/Tests/Features/Players/ListTests.cs
src/Tests/Features/Teams/DetailTests.cs
src/Tests/Features/Teams/DropPlayerTests.cs
src/Tests/Features/Teams/ListTests.cs
src/Tests/Features/Teams/SignPlayerTests.cs
src/Tests/IntegrationTestBase.cs
src/Tests/RedirectTests.cs

- Reduce amount of time tests take to run by 20%.
- Reduce complexity of test setups, fixtures, etc by removing a lot of code out of `IntegrationTesting.cs`
Closes #154

Test improvements

---

src/Client/App.razor
src/Client/Features/Authentication.razor
src/Client/Shared/AuthenticatedLayout.razor
src/Client/Shared/MainLayout.razor
src/Client/Shared/NavMenu/Admin.razor
src/Client/Shared/NavMenu/Login.razor
src/Client/Shared/UnauthenticatedLayout.razor
src/Client/_Imports.razor
src/Server/Infrastructure/SeedDataCommand.cs
src/Shared/Infastructure/Identity/ApplicationAuthorizationRequirements.cs
src/Shared/Infastructure/Identity/IUser.cs
src/Tests/Features/FreeAgents/AddBidTests.cs
src/Tests/Shared/AuthenticatedLayoutTests.cs
src/Tests/UITestBase.cs

Add better UX around admin approval.

---

.github/workflows/dotnet.yml

cleanup workflow file

---

.github/workflows/dotnet.yml
src/Client/Features/Dashboard/ChangeList.razor
src/Client/Features/Rules/Fines.razor
src/Client/Features/Rules/FranchisedPlayers.razor
src/Client/Features/Rules/TradeWaiver.razor

Small bug/formatting fixes
